// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people4.proto

package com.ctrip.flight.grpc4;

public interface PeopleResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.grpc4.PeopleResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ctrip.flight.grpc4.PeopleResponse peopleResponse = 1;</code>
   */
  java.util.List<com.ctrip.flight.grpc4.PeopleResponse> 
      getPeopleResponseList();
  /**
   * <code>repeated .com.ctrip.flight.grpc4.PeopleResponse peopleResponse = 1;</code>
   */
  com.ctrip.flight.grpc4.PeopleResponse getPeopleResponse(int index);
  /**
   * <code>repeated .com.ctrip.flight.grpc4.PeopleResponse peopleResponse = 1;</code>
   */
  int getPeopleResponseCount();
  /**
   * <code>repeated .com.ctrip.flight.grpc4.PeopleResponse peopleResponse = 1;</code>
   */
  java.util.List<? extends com.ctrip.flight.grpc4.PeopleResponseOrBuilder> 
      getPeopleResponseOrBuilderList();
  /**
   * <code>repeated .com.ctrip.flight.grpc4.PeopleResponse peopleResponse = 1;</code>
   */
  com.ctrip.flight.grpc4.PeopleResponseOrBuilder getPeopleResponseOrBuilder(
      int index);
}
