// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people4.proto

package com.ctrip.flight.grpc4;

public final class People4Proto {
  private People4Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc4_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc4_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc4_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc4_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc4_PeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc4_PeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc4_PeopleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc4_PeopleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc4_PeopleResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc4_PeopleResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc4_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc4_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc4_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc4_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpeople4.proto\022\026com.ctrip.flight.grpc4\"" +
      "\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResp" +
      "onse\022\020\n\010realname\030\001 \001(\t\"\034\n\rPeopleRequest\022" +
      "\013\n\003age\030\001 \001(\005\"9\n\016PeopleResponse\022\014\n\004name\030\001" +
      " \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"T\n\022Peopl" +
      "eResponseList\022>\n\016peopleResponse\030\001 \003(\0132&." +
      "com.ctrip.flight.grpc4.PeopleResponse\"%\n" +
      "\rStreamRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016" +
      "StreamResponse\022\025\n\rresponse_info\030\001 \001(\t2\250\003" +
      "\n\rPeopleService\022`\n\025GetRealNameByUsername" +
      "\022!.com.ctrip.flight.grpc4.MyRequest\032\".co" +
      "m.ctrip.flight.grpc4.MyResponse\"\000\022d\n\017Get" +
      "PeoplesByAge\022%.com.ctrip.flight.grpc4.Pe" +
      "opleRequest\032&.com.ctrip.flight.grpc4.Peo" +
      "pleResponse\"\0000\001\022p\n\027GetPeoplesWrapperByAg" +
      "es\022%.com.ctrip.flight.grpc4.PeopleReques" +
      "t\032*.com.ctrip.flight.grpc4.PeopleRespons" +
      "eList\"\000(\001\022]\n\006BiTalk\022%.com.ctrip.flight.g" +
      "rpc4.StreamRequest\032&.com.ctrip.flight.gr" +
      "pc4.StreamResponse\"\000(\0010\001B(\n\026com.ctrip.fl" +
      "ight.grpc4B\014People4ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ctrip_flight_grpc4_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ctrip_flight_grpc4_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc4_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_ctrip_flight_grpc4_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ctrip_flight_grpc4_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc4_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_ctrip_flight_grpc4_PeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ctrip_flight_grpc4_PeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc4_PeopleRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_ctrip_flight_grpc4_PeopleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ctrip_flight_grpc4_PeopleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc4_PeopleResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_ctrip_flight_grpc4_PeopleResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ctrip_flight_grpc4_PeopleResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc4_PeopleResponseList_descriptor,
        new java.lang.String[] { "PeopleResponse", });
    internal_static_com_ctrip_flight_grpc4_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ctrip_flight_grpc4_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc4_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_ctrip_flight_grpc4_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_ctrip_flight_grpc4_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc4_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
