// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people4.proto

package com.ctrip.flight.grpc4;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.grpc4.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
