// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package com.ctrip.flight.grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.grpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 视频里为什么是2？
   * </pre>
   *
   * <code>string realname = 1;</code>
   */
  java.lang.String getRealname();
  /**
   * <pre>
   * 视频里为什么是2？
   * </pre>
   *
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
