// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people3.proto

package com.ctrip.flight.grpc3;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.grpc3.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
