// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people3.proto

package com.ctrip.flight.grpc3;

/**
 * Protobuf type {@code com.ctrip.flight.grpc3.PeopleResponseList}
 */
public  final class PeopleResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.grpc3.PeopleResponseList)
    PeopleResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PeopleResponseList.newBuilder() to construct.
  private PeopleResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PeopleResponseList() {
    peopleResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PeopleResponseList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PeopleResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              peopleResponse_ = new java.util.ArrayList<com.ctrip.flight.grpc3.PeopleResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            peopleResponse_.add(
                input.readMessage(com.ctrip.flight.grpc3.PeopleResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        peopleResponse_ = java.util.Collections.unmodifiableList(peopleResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.grpc3.People3Proto.internal_static_com_ctrip_flight_grpc3_PeopleResponseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.grpc3.People3Proto.internal_static_com_ctrip_flight_grpc3_PeopleResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.grpc3.PeopleResponseList.class, com.ctrip.flight.grpc3.PeopleResponseList.Builder.class);
  }

  public static final int PEOPLERESPONSE_FIELD_NUMBER = 1;
  private java.util.List<com.ctrip.flight.grpc3.PeopleResponse> peopleResponse_;
  /**
   * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
   */
  public java.util.List<com.ctrip.flight.grpc3.PeopleResponse> getPeopleResponseList() {
    return peopleResponse_;
  }
  /**
   * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
   */
  public java.util.List<? extends com.ctrip.flight.grpc3.PeopleResponseOrBuilder> 
      getPeopleResponseOrBuilderList() {
    return peopleResponse_;
  }
  /**
   * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
   */
  public int getPeopleResponseCount() {
    return peopleResponse_.size();
  }
  /**
   * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
   */
  public com.ctrip.flight.grpc3.PeopleResponse getPeopleResponse(int index) {
    return peopleResponse_.get(index);
  }
  /**
   * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
   */
  public com.ctrip.flight.grpc3.PeopleResponseOrBuilder getPeopleResponseOrBuilder(
      int index) {
    return peopleResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < peopleResponse_.size(); i++) {
      output.writeMessage(1, peopleResponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < peopleResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, peopleResponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.grpc3.PeopleResponseList)) {
      return super.equals(obj);
    }
    com.ctrip.flight.grpc3.PeopleResponseList other = (com.ctrip.flight.grpc3.PeopleResponseList) obj;

    if (!getPeopleResponseList()
        .equals(other.getPeopleResponseList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPeopleResponseCount() > 0) {
      hash = (37 * hash) + PEOPLERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getPeopleResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.grpc3.PeopleResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.grpc3.PeopleResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.grpc3.PeopleResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.grpc3.PeopleResponseList)
      com.ctrip.flight.grpc3.PeopleResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.grpc3.People3Proto.internal_static_com_ctrip_flight_grpc3_PeopleResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.grpc3.People3Proto.internal_static_com_ctrip_flight_grpc3_PeopleResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.grpc3.PeopleResponseList.class, com.ctrip.flight.grpc3.PeopleResponseList.Builder.class);
    }

    // Construct using com.ctrip.flight.grpc3.PeopleResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPeopleResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (peopleResponseBuilder_ == null) {
        peopleResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        peopleResponseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.grpc3.People3Proto.internal_static_com_ctrip_flight_grpc3_PeopleResponseList_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.grpc3.PeopleResponseList getDefaultInstanceForType() {
      return com.ctrip.flight.grpc3.PeopleResponseList.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.grpc3.PeopleResponseList build() {
      com.ctrip.flight.grpc3.PeopleResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.grpc3.PeopleResponseList buildPartial() {
      com.ctrip.flight.grpc3.PeopleResponseList result = new com.ctrip.flight.grpc3.PeopleResponseList(this);
      int from_bitField0_ = bitField0_;
      if (peopleResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          peopleResponse_ = java.util.Collections.unmodifiableList(peopleResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.peopleResponse_ = peopleResponse_;
      } else {
        result.peopleResponse_ = peopleResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.grpc3.PeopleResponseList) {
        return mergeFrom((com.ctrip.flight.grpc3.PeopleResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.grpc3.PeopleResponseList other) {
      if (other == com.ctrip.flight.grpc3.PeopleResponseList.getDefaultInstance()) return this;
      if (peopleResponseBuilder_ == null) {
        if (!other.peopleResponse_.isEmpty()) {
          if (peopleResponse_.isEmpty()) {
            peopleResponse_ = other.peopleResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePeopleResponseIsMutable();
            peopleResponse_.addAll(other.peopleResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.peopleResponse_.isEmpty()) {
          if (peopleResponseBuilder_.isEmpty()) {
            peopleResponseBuilder_.dispose();
            peopleResponseBuilder_ = null;
            peopleResponse_ = other.peopleResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            peopleResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPeopleResponseFieldBuilder() : null;
          } else {
            peopleResponseBuilder_.addAllMessages(other.peopleResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.grpc3.PeopleResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.grpc3.PeopleResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ctrip.flight.grpc3.PeopleResponse> peopleResponse_ =
      java.util.Collections.emptyList();
    private void ensurePeopleResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        peopleResponse_ = new java.util.ArrayList<com.ctrip.flight.grpc3.PeopleResponse>(peopleResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.grpc3.PeopleResponse, com.ctrip.flight.grpc3.PeopleResponse.Builder, com.ctrip.flight.grpc3.PeopleResponseOrBuilder> peopleResponseBuilder_;

    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public java.util.List<com.ctrip.flight.grpc3.PeopleResponse> getPeopleResponseList() {
      if (peopleResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(peopleResponse_);
      } else {
        return peopleResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public int getPeopleResponseCount() {
      if (peopleResponseBuilder_ == null) {
        return peopleResponse_.size();
      } else {
        return peopleResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public com.ctrip.flight.grpc3.PeopleResponse getPeopleResponse(int index) {
      if (peopleResponseBuilder_ == null) {
        return peopleResponse_.get(index);
      } else {
        return peopleResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder setPeopleResponse(
        int index, com.ctrip.flight.grpc3.PeopleResponse value) {
      if (peopleResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeopleResponseIsMutable();
        peopleResponse_.set(index, value);
        onChanged();
      } else {
        peopleResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder setPeopleResponse(
        int index, com.ctrip.flight.grpc3.PeopleResponse.Builder builderForValue) {
      if (peopleResponseBuilder_ == null) {
        ensurePeopleResponseIsMutable();
        peopleResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        peopleResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder addPeopleResponse(com.ctrip.flight.grpc3.PeopleResponse value) {
      if (peopleResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeopleResponseIsMutable();
        peopleResponse_.add(value);
        onChanged();
      } else {
        peopleResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder addPeopleResponse(
        int index, com.ctrip.flight.grpc3.PeopleResponse value) {
      if (peopleResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeopleResponseIsMutable();
        peopleResponse_.add(index, value);
        onChanged();
      } else {
        peopleResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder addPeopleResponse(
        com.ctrip.flight.grpc3.PeopleResponse.Builder builderForValue) {
      if (peopleResponseBuilder_ == null) {
        ensurePeopleResponseIsMutable();
        peopleResponse_.add(builderForValue.build());
        onChanged();
      } else {
        peopleResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder addPeopleResponse(
        int index, com.ctrip.flight.grpc3.PeopleResponse.Builder builderForValue) {
      if (peopleResponseBuilder_ == null) {
        ensurePeopleResponseIsMutable();
        peopleResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        peopleResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder addAllPeopleResponse(
        java.lang.Iterable<? extends com.ctrip.flight.grpc3.PeopleResponse> values) {
      if (peopleResponseBuilder_ == null) {
        ensurePeopleResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, peopleResponse_);
        onChanged();
      } else {
        peopleResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder clearPeopleResponse() {
      if (peopleResponseBuilder_ == null) {
        peopleResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        peopleResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public Builder removePeopleResponse(int index) {
      if (peopleResponseBuilder_ == null) {
        ensurePeopleResponseIsMutable();
        peopleResponse_.remove(index);
        onChanged();
      } else {
        peopleResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public com.ctrip.flight.grpc3.PeopleResponse.Builder getPeopleResponseBuilder(
        int index) {
      return getPeopleResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public com.ctrip.flight.grpc3.PeopleResponseOrBuilder getPeopleResponseOrBuilder(
        int index) {
      if (peopleResponseBuilder_ == null) {
        return peopleResponse_.get(index);  } else {
        return peopleResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public java.util.List<? extends com.ctrip.flight.grpc3.PeopleResponseOrBuilder> 
         getPeopleResponseOrBuilderList() {
      if (peopleResponseBuilder_ != null) {
        return peopleResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(peopleResponse_);
      }
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public com.ctrip.flight.grpc3.PeopleResponse.Builder addPeopleResponseBuilder() {
      return getPeopleResponseFieldBuilder().addBuilder(
          com.ctrip.flight.grpc3.PeopleResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public com.ctrip.flight.grpc3.PeopleResponse.Builder addPeopleResponseBuilder(
        int index) {
      return getPeopleResponseFieldBuilder().addBuilder(
          index, com.ctrip.flight.grpc3.PeopleResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ctrip.flight.grpc3.PeopleResponse peopleResponse = 1;</code>
     */
    public java.util.List<com.ctrip.flight.grpc3.PeopleResponse.Builder> 
         getPeopleResponseBuilderList() {
      return getPeopleResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.grpc3.PeopleResponse, com.ctrip.flight.grpc3.PeopleResponse.Builder, com.ctrip.flight.grpc3.PeopleResponseOrBuilder> 
        getPeopleResponseFieldBuilder() {
      if (peopleResponseBuilder_ == null) {
        peopleResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.flight.grpc3.PeopleResponse, com.ctrip.flight.grpc3.PeopleResponse.Builder, com.ctrip.flight.grpc3.PeopleResponseOrBuilder>(
                peopleResponse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        peopleResponse_ = null;
      }
      return peopleResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.grpc3.PeopleResponseList)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.grpc3.PeopleResponseList)
  private static final com.ctrip.flight.grpc3.PeopleResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.grpc3.PeopleResponseList();
  }

  public static com.ctrip.flight.grpc3.PeopleResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeopleResponseList>
      PARSER = new com.google.protobuf.AbstractParser<PeopleResponseList>() {
    @java.lang.Override
    public PeopleResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PeopleResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PeopleResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeopleResponseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.grpc3.PeopleResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

