// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people3.proto

package com.ctrip.flight.grpc3;

public interface PeopleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.grpc3.PeopleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
