// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people3.proto

package com.ctrip.flight.grpc3;

public final class People3Proto {
  private People3Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc3_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc3_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc3_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc3_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc3_PeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc3_PeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc3_PeopleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc3_PeopleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc3_PeopleResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc3_PeopleResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpeople3.proto\022\026com.ctrip.flight.grpc3\"" +
      "\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResp" +
      "onse\022\020\n\010realname\030\001 \001(\t\"\034\n\rPeopleRequest\022" +
      "\013\n\003age\030\001 \001(\005\"9\n\016PeopleResponse\022\014\n\004name\030\001" +
      " \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"T\n\022Peopl" +
      "eResponseList\022>\n\016peopleResponse\030\001 \003(\0132&." +
      "com.ctrip.flight.grpc3.PeopleResponse2\311\002" +
      "\n\rPeopleService\022`\n\025GetRealNameByUsername" +
      "\022!.com.ctrip.flight.grpc3.MyRequest\032\".co" +
      "m.ctrip.flight.grpc3.MyResponse\"\000\022d\n\017Get" +
      "PeoplesByAge\022%.com.ctrip.flight.grpc3.Pe" +
      "opleRequest\032&.com.ctrip.flight.grpc3.Peo" +
      "pleResponse\"\0000\001\022p\n\027GetPeoplesWrapperByAg" +
      "es\022%.com.ctrip.flight.grpc3.PeopleReques" +
      "t\032*.com.ctrip.flight.grpc3.PeopleRespons" +
      "eList\"\000(\001B(\n\026com.ctrip.flight.grpc3B\014Peo" +
      "ple3ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ctrip_flight_grpc3_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ctrip_flight_grpc3_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc3_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_ctrip_flight_grpc3_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ctrip_flight_grpc3_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc3_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_ctrip_flight_grpc3_PeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ctrip_flight_grpc3_PeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc3_PeopleRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_ctrip_flight_grpc3_PeopleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ctrip_flight_grpc3_PeopleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc3_PeopleResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_ctrip_flight_grpc3_PeopleResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ctrip_flight_grpc3_PeopleResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc3_PeopleResponseList_descriptor,
        new java.lang.String[] { "PeopleResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
