// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people2.proto

package com.ctrip.flight.grpc2;

public final class People2Proto {
  private People2Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc2_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc2_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc2_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc2_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc2_PeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc2_PeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ctrip_flight_grpc2_PeopleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ctrip_flight_grpc2_PeopleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpeople2.proto\022\026com.ctrip.flight.grpc2\"" +
      "\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResp" +
      "onse\022\020\n\010realname\030\001 \001(\t\"\034\n\rPeopleRequest\022" +
      "\013\n\003age\030\001 \001(\005\"9\n\016PeopleResponse\022\014\n\004name\030\001" +
      " \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t2\327\001\n\rPeop" +
      "leService\022`\n\025GetRealNameByUsername\022!.com" +
      ".ctrip.flight.grpc2.MyRequest\032\".com.ctri" +
      "p.flight.grpc2.MyResponse\"\000\022d\n\017GetPeople" +
      "sByAge\022%.com.ctrip.flight.grpc2.PeopleRe" +
      "quest\032&.com.ctrip.flight.grpc2.PeopleRes" +
      "ponse\"\0000\001B(\n\026com.ctrip.flight.grpc2B\014Peo" +
      "ple2ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ctrip_flight_grpc2_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ctrip_flight_grpc2_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc2_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_ctrip_flight_grpc2_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ctrip_flight_grpc2_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc2_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_ctrip_flight_grpc2_PeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ctrip_flight_grpc2_PeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc2_PeopleRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_ctrip_flight_grpc2_PeopleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ctrip_flight_grpc2_PeopleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ctrip_flight_grpc2_PeopleResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
